= Integration of Lunr in Antora
:ci-url: https://travis-ci.org/Mogztter/antora-lunr
:ci-img: {ci-url}.svg?branch=master
:npm-img: https://img.shields.io/npm/v/antora-lunr.svg
:npm-url: https://www.npmjs.org/package/antora-lunr

image:{ci-img}[Build Status (Travis CI), link={ci-url}]
image:{npm-img}[NPM Package, link={https://www.npmjs.org/package/antora-lunr}]

link:https://lunrjs.com/[Lunr] provides a great search experience without the need for external, server-side, search services.
It makes it possible to add an *offline* search engine in your Antora's documentation site.

== Usage

NOTE: This requires a not-merged feature in Antora, an implementation of the proposed link:https://gitlab.com/antora/antora/issues/377[event-driven plugin system].
This are available in https://gitlab.com/djencks/antora branch `issue-377-events`.

There are two aspects to using lunr with Antora:

* Generate the index during site generation.
* Display the search facility in the UI.

=== Generate an index file

This is done by registering this plugin with the Antora project.

Since this requires a non-standard Antora, you need to clone https://gitlab.com/djencks/antora.git and checkout the `issue-377-events` branch.
Run `yarn` or `npm install` as you prefer.
For convenience, set up an easy way to reference this:

[source, shell]
----
export ANTORA_DEV=<path to this antora checkout>/node_modules/.bin/antora
----

Since this branch is not yet available from npm, you need to clone the project, lets say to `~/antora-lunr`.

Now you can run specifying the plugin on the command line:

[source, shell]
----
$ANTORA_DEV antora-playbook.yml --plugin ~/antora-lunr
----

or modify your playbook to specify the plugin:

[source,yml]
----
plugins:
  - /Users/david/projects/antora/antora-lunr/antora-lunr/lib/generate-index.js
----
In the playbook you can use an absolute path or path relative to the playbook, but not (currently) a `~/` path.

=== Enable the search component in the UI

Now that we have a `search-index.js`, we need to enable the search component in the UI.

==== If you are using the default UI or for a quick experiment

Copy the `supplemental_ui` directory in your Antora playbook repository and configure a `supplemental_files`:

[source,yml]
----
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui
----

==== Generate the site

Generate your documentation site with the following environment variables:

* `DOCSEARCH_ENABLED=true`
* `DOCSEARCH_ENGINE=lunr`

For instance, as a command line:

[source,console]
----
$ DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr antora site.yml
----

==== To add this functionality to a customized UI

Assuming your UI bundle project is set up similarly to the Antora default UI project, there are two actions:

. Copy the css and js from the supplemental_ui directory to the corresponding locations in your UI project.
. Modify the appropriate partials to include the important content from the supplemental_ui partials:

.footer-scripts.hbs
[source,html]
----
<script type="text/javascript">
  window.antora = window.antora || {}
  window.antora.basePath = '{{or siteRootPath (or site.url siteRootUrl)}}'
  window.antora.pagePath = '{{@root.page.url}}'
</script>
<script src="{{uiRootPath}}/js/vendor/lunr.js"></script>
<script src="{{uiRootPath}}/js/vendor/search.js"></script>
<script async src="{{uiRootPath}}/../search-index.js"></script>
----

.head-styles.hbs
[source,html]
----
      <link rel="stylesheet" href="{{uiRootPath}}/css/search.css">
----

.header-content.hbs in the `navbar-brand` div
[source,html]
----
      <div class="navbar-item">
        <input id="search-input" type="text" placeholder="Search docs">
      </div>
----

In this case no env vars are needed.

==== General UI notes

NOTE: For this to function correctly you must provide the `site.url` key in your playbook file.
See the Antora docs on the link:https://docs.antora.org/antora/1.1/playbook/playbook-schema/[playbook schema].
If using the site locally (not serving from a web server) then you can set your `site.url` to a `file://` reference, e.g. `file:///home/documents/antora/website/public/`.

TIP: If you are using link:https://www.npmjs.com/package/serve[serve] HTTP server to view your site locally,
set the `site.url` to `http://localhost:5000`.


=== Testing this module

In the root of the repository, run `npm t`.
